name: 'Build - Debug mode'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
